version: '3.8'

services:
  web:
    build: .
    ports:
      - "5009:5009"
    volumes:
      - .:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    command: python app.py
